# Generated by Django 6.1.1 on 2026-09-09 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de atualização')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi excluído (soft delete)', null=True, verbose_name='Data de exclusão')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('account_type', models.CharField(choices=[('bank', 'Conta Bancaria'), ('wallet', 'Carteira'), ('credit_card', 'Cartão de Crédito'), ('investment', 'Investimento')], default='bank', max_length=20, verbose_name='Tipo de Conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Inicial')),
                ('color_hex', models.CharField(default='#319795', max_length=7, verbose_name='Cor')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'db_table': 'finance_account',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de atualização')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi excluído (soft delete)', null=True, verbose_name='Data de exclusão')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_type', models.CharField(choices=[('income', 'receitas'), ('expenses', 'despesas')], max_length=20, verbose_name='Tipo da Categoria')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icone')),
                ('cor_hex', models.CharField(default='#2B6CB0', max_length=7, verbose_name='Cor da Categoria')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='finance.category', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'db_table': 'finance_category',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de atualização')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi excluído (soft delete)', null=True, verbose_name='Data de exclusão')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('transaction_date', models.DateField(verbose_name='Data da Transação')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('transaction_type', models.CharField(choices=[('income', 'receitas'), ('expenses', 'despesas'), ('transference', 'transferência')], max_length=20, verbose_name='Tipo de Transação')),
                ('transaction_status', models.CharField(choices=[('pending', 'pendente'), ('completed', 'Completada'), ('canceled', 'cancelada')], default='completed', max_length=20, verbose_name='Status da Transação')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account', verbose_name='Conta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category', verbose_name='Categoria')),
                ('destiny_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='finance.account', verbose_name='Conta Destino')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'finance_transaction',
                'ordering': ['-transaction_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de atualização')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi excluído (soft delete)', null=True, verbose_name='Data de exclusão')),
                ('limit_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month_reference', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year_reference', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de Referência')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Orçamento Mensal',
                'verbose_name_plural': 'Orçamentos Mensais',
                'db_table': 'finance_budget',
                'ordering': ['-year_reference', '-month_reference'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('category', 'month_reference', 'year_reference'), name='unique_active_budget_per_category_period')],
            },
        ),
    ]
