# Generated by Django 6.1.1 on 2026-09-10 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de atualização')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data em que o registro foi excluído (soft delete)', null=True, verbose_name='Data de exclusão')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('recurring_type', models.CharField(choices=[('income', 'receitas'), ('expenses', 'despesas')], max_length=20, verbose_name='Tipo de Transação')),
                ('frequency', models.CharField(choices=[('monthly', 'mensal'), ('weekly', 'semanal'), ('annual', 'anual')], default='monthly', max_length=20, verbose_name='Frequência')),
                ('due_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Transação Recorrente',
                'verbose_name_plural': 'Transações Recorrentes',
                'db_table': 'finance_recurring_transaction',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='account_created_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['updated_at'], name='account_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['deleted_at'], name='account_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['created_at'], name='budget_created_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['updated_at'], name='budget_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['deleted_at'], name='budget_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['updated_at'], name='category_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['deleted_at'], name='category_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['updated_at'], name='transaction_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['deleted_at'], name='transaction_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='transaction_date_idx'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to='finance.account', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias', to='finance.category', verbose_name='Categoria'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['created_at'], name='recurring_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['updated_at'], name='recurring_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['deleted_at'], name='recurring_deleted_idx'),
        ),
    ]
